web:
    build: .
    ports:
     - "5000:80"
    links:
     - db
    environment:
     - DB_HOST=localhost
     - DB_DRIVER=PDO
     - DB_USER=root
     - DB_PASS=root
db:
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
