-- MySQL Script generated by MySQL Workbench
-- Wed 03 Jan 2018 09:51:30 PM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema basic-service
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `basic-service` ;

-- -----------------------------------------------------
-- Schema basic-service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `basic-service` DEFAULT CHARACTER SET utf8 ;
USE `basic-service` ;

-- -----------------------------------------------------
-- Table `basic-service`.`jigs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `basic-service`.`jigs` ;

CREATE TABLE IF NOT EXISTS `basic-service`.`jigs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `parent_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `basic-service`.`jig_parents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `basic-service`.`jig_parents` ;

CREATE TABLE IF NOT EXISTS `basic-service`.`jig_parents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `basic-service`.`jigs_jig_children`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `basic-service`.`jigs_jig_children` ;

CREATE TABLE IF NOT EXISTS `basic-service`.`jigs_jig_children` (
  `jig_id` INT NOT NULL,
  `jig_child_id` INT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `basic-service`.`jig_children`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `basic-service`.`jig_children` ;

CREATE TABLE IF NOT EXISTS `basic-service`.`jig_children` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
